### ISSUE TITLE
3D Models Incomplete, Path Problem on Some

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-#39]
**Is your feature request related to a problem? Please describe.**
The 3D view of the printed wiring assembly is incomplete
![image](https://github.com/user-attachments/assets/7ea91c18-069a-4687-8b9a-48e569839559)
For example the power jack is not represented.
Also missing is the very important ESP32 Kit

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
3D models for all parts on PCB and the ESP32 Kit so that a full 3D STEP file can be exported to aid enclosure design task.

**Additional context**
_Add any other context or screenshots about the feature request here._

Note for the Power Jack there is an error in the path to the 3D model the root cause of which should be investigated
![image](https://github.com/user-attachments/assets/ae999d3d-9845-48aa-98dc-4565c86b73d6)

**Comment by ForrestErickson** [comment]
Note: Generation of STEP file reports the many missing 3D models

![image](https://github.com/user-attachments/assets/59edde5a-00cb-4702-9001-653cf801e83b)

Here is the resulting 3D file (which I have not and will not check in) opened in FreeCAD A2plus work bench.
![image](https://github.com/user-attachments/assets/2d50ff09-08cb-4632-ac8b-3ffd1a5e947f)

CC: @samoyin

**Comment by nk25719** [comment]
Issee #67 shows how we fixed the Path Problem for the 3D models of the parts. 


<img width="417" alt="image" src="https://github.com/user-attachments/assets/e51a45d0-2d06-4f6c-91fb-aafad8399f24">



cc: @ForrestErickson 


Closing.
