### ISSUE TITLE
From KiCad, Export a STEP (? other types) file of Printed Wiring Assembly, May Help Enclosure Design

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-#40]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

Problem, For design of an enclosure, a CAD file of the Printed Wiring Assembly will help.
With a 3D file fit into the enclosure may be tested, and confirmed.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
The PCB designer should export from KiCad the assembly in a STEP file format (Or any other useful format)

**Additional context**
_Add any other context or screenshots about the feature request here._

Here is screen shot of the path to file export
![image](https://github.com/user-attachments/assets/10e8b6b8-a92d-44af-a327-9b4dba15105f)

Here is the STEP export dialog
![image](https://github.com/user-attachments/assets/355f62d9-5251-4803-b038-b2e9594b0d27)
There are several 3D model types. Choose which ever works best for the user of this file (the person designing the enclosure for example, Trial and experimentation may be required.)

Note the options for setting the Coordinates. Choose which ever works best for the user of this file (the person designing the enclosure for example, Trial and experimentation may be required.)

**Comment by ForrestErickson** [comment]
@samoyin 
Are you experienced enough with OpenSCAD to know if it is possible to import a STEP file to help your work?

I use FreeCAD.
In FreeCAD I can import into an assembly work bench the STEP file generated by KiCad. Please see the issue: https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/issues/41

CC: @nk25719

**Comment by samoyin** [comment]
Hello Lee,
 I have not done this before but there is a way to import a STEP file to OpenScad and convert the Step file to an OpenScad program. Also, I saw your most recent email. I hope you rest and recover well from the surgery. See you when you get better!!!
From Oyin.
________________________________

**Comment by nk25719** [comment]
From Kicad project manager we navagate to the PCB editor and we click on file then export and we chose the STEP file format to do an export, we chose the path we want to export the STEP file into and we do the export:

1.  <img width="252" alt="image" src="https://github.com/user-attachments/assets/93315bae-c0db-42f1-87a2-0220d1ad992f">

2.   <img width="462" alt="image" src="https://github.com/user-attachments/assets/30013f22-cbfc-449c-b91b-45fc7f43aff2">



-----

### **The STEP file format of the Homework2 PCBa**
<img width="591" alt="image" src="https://github.com/user-attachments/assets/8d1ee588-776d-484b-a136-a312c461bc83">
