### ISSUE TITLE
Inconsistant Naming, Wrong Naming of Button Pins Firmware versus Schematic Version 1 PCB

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-#45]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
The name of GPIO pins on the schematic and PCB should match the naming in firmware.
Names should reflect function.

However for example S1 is called "S1-morseCodeDanger1" on the schematic and PCB and connected to GPIO36
![image](https://github.com/user-attachments/assets/dab773f0-e439-4e66-b800-1469ebfa1d35)
![image](https://github.com/user-attachments/assets/f8772f8d-92d6-409b-9db7-89490460659b)

But in the firmware is const int MUTE_BUTTON_PIN = 36; // GPIO 36 for the mute button

These names are inconsistent.
In all firmware other pins and pin names should be reviewed and corrected where errors are found.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

Change in all firmware to reflect the actual name on the schematic and PCB (and / or possibly Krake)

**Comment by ForrestErickson** [comment]
Note the exact text on the schematic for the switches has a "-" which is not a character that can be used in a variable name.
Example: S1-morseCodeDanger1
So change to S1_morseCodeDanger1

### Lesson Learned
In future use only upper case letters and numbers and underscore for net names which will be referenced in firmware.

**Comment by nk25719** [comment]
During the process of transferring the PMD into a Krake, the switches and the LED were renamed.

PMD inherrited MUTE_BUTTON_PIN = 36; // GPIO 36 for the mute button from Krake

**Comment by nk25719** [comment]
cc: @ForrestErickson 

Closing.
