### ISSUE TITLE
Update Firmware, Factory Test FactoryTest_WW_WZ_BUTTONS to report Program Name and Version on Serial Port

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-#46]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
The factory test firmware such as FactoryTest_WW_WZ_BUTTONS should report the program name and version on the serial port so that users can know if they are using the correct firmware.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

Look at the GPAD factory test code for some good practices
https://github.com/PubInv/general-purpose-alarm-device/blob/main/Firmware/GPAD_Factory_Test/GPAD_Factory_Test.ino

**Comment by nk25719** [comment]
Adding Serial splash to report prog name, firmware version, date and time of firmware compilation 


[FactoryTest_WW_WZ_BUTTONS.zip](https://github.com/user-attachments/files/17869206/FactoryTest_WW_WZ_BUTTONS.zip)

Closing.
