### ISSUE TITLE
Hardware Bug - LED D8 is ON while No Power Connection on Barrel Jack J1

### ISSUE THREAD

**Issue by nk25719** [nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-#54]
**Describe the Failure / Bug**
A clear and concise description of what the failure / bug is.
Short Summary of the expected behavior:
Short Summary of the buggy behavior:

**Device Under Test, aka DUT**
1. Model Number:   
2. Serial Number(s):   
3. Location where failure / bug occurred
4. Hardware configuration. (How connected, any accessories, what else it takes to replicate the system in which the failure occurred.)
5. Extent of Failure
** Is failure intermittent?
** Is failure fixed by power cycling?
** Is failure perminant?

**To Reproduce**

**Expected behavior**
_LED D8 turnung on when the PCBa is connected to power through Barrel Jack J1_

**Screenshots**

**Hardware description
Model:
Serial Number:
Other:

**Test Equipment
Model:
Serial Number:

**Additional context**

**Comment by nk25719** [comment]
<img width="499" alt="image" src="https://github.com/user-attachments/assets/8d4944ff-5297-43a7-ab1d-fcb0c3ab7376">

**Comment by ForrestErickson** [comment]
Please review the now closed issue: #47 
https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/issues/47

**Comment by nk25719** [comment]
Reviewed and solved in issue #47  

cc: @ForrestErickson 

Closing.
