### ISSUE TITLE
Add Serial Port and LCD Splash Screen 

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-#56]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
I am frustrated when I do not know the name and version of the firmware in an embedded system.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
Add in the setup() some code to report the desired information on serial port. Here is an example
![image](https://github.com/user-attachments/assets/316c9bb8-0a55-4a59-98f6-393ca2fa81eb)

Add in the setup() some code to report the desired information on the LCD

**Comment by ForrestErickson** [comment]
Here is a modified file with some examples.
This code also reports the date and time of the compile.


[PMDtoKRake_KrakeV2.zip](https://github.com/user-attachments/files/17091891/PMDtoKRake_KrakeV2.zip)

**Comment by ForrestErickson** [comment]
Here is the 28 September work.
[PMDtoKRake_KrakeV220240928_1129.zip](https://github.com/user-attachments/files/17174913/PMDtoKRake_KrakeV220240928_1129.zip)

**Comment by nk25719** [comment]
Adding changes to krake's firmware...

**Comment by ForrestErickson** [comment]
Note in the "[DFPlayerTD5580ATest.zip](https://github.com/user-attachments/files/17182320/DFPlayerTD5580ATest.zip)" file the serial splash message.

**Comment by nk25719** [comment]
```
 Serial.println("===================================");
  Serial.println(DEVICE_UNDER_TEST);
  Serial.print(PROG_NAME);
  Serial.println(VERSION);
  Serial.print("Compiled at: ");
  Serial.println(F(__DATE__ " " __TIME__) ); //compile date that is used for a unique identifier
  Serial.println("===================================");
  Serial.println();

```


Closing.

**Comment by nk25719** [comment]
<img width="396" alt="image" src="https://github.com/user-attachments/assets/879bc9c0-ce50-471b-b1cb-bb230b0e2d08">
