### ISSUE TITLE
Please see Krake issue number 60 for key cap

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-#66]
**Is your feature request related to a problem? Please describe.**

Please see Krake issue number 60
https://github.com/PubInv/krake/issues/60

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nk25719** [comment]
cc: @samoyin

**Comment by nk25719** [comment]
<img width="430" alt="image" src="https://github.com/user-attachments/assets/7aac9c2c-5c77-4510-9914-cbd0dd150bec">

cc: @ForrestErickson @samoyin
