### ISSUE TITLE
Hardware Bug_Incompatible (x) width of the front panel with the box of the enclosure.

### ISSUE THREAD

**Issue by samoyin** [nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-#68]
**Describe the Failure / Bug**
A clear and concise description of what the failure/bug is: The box is not shutting close with the front panel, The x width of the front panel = 62.2mm and the internal x width of the box = 60.8mm.
Short Summary of the expected behavior: A closed enclosure
Short Summary of the buggy behavior: 
![image](https://github.com/user-attachments/assets/3235bb72-ea90-4fc1-a3ca-76ba68ab05a3)

**Comment by samoyin** [comment]
![image](https://github.com/user-attachments/assets/186506b8-4010-4bb8-82ed-e820bbb68b73)
Refinement of measurements to add allowance between the front panel and the box of the enclosure.
path: EnclosureREVc.scad

**Comment by nk25719** [comment]
CC: @ForrestErickson
