### ISSUE TITLE
File Management 

### ISSUE THREAD

**Issue by nk25719** [nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-#69]
**Is your  request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
 The sCAD files are not filed correctly 
 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
 Use git mv to move EnclosureREVb.scad and EnclosureREVc.scad to the folder Enclosure_and_Workbench

**Comment by samoyin** [comment]
I have moved the EnclosureREV.scad files into the Enclosure_and_Workbench folder.
I used this code on the git bash shell.
![image](https://github.com/user-attachments/assets/83fabd51-ea6a-43f6-abce-e4941f1d3594)
I have for you here a screenshot of the new location.
![image](https://github.com/user-attachments/assets/dc6db727-acae-49a9-b3a5-597b41c1e4b2)
