### ISSUE TITLE
LED Separator

### ISSUE THREAD

**Issue by nk25719** [nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-#70]
**Is your feature request related to a problem? Please describe.**
No tool is available to support LED assembly in a way that ensures they are positioned at a consistent and stable height. To allow all LEDs to be at the same level, high enough to be visible from the top of the front panel, while also maintaining a uniform distance between each LED.

**Describe the solution you'd like**
3D Model Seperator 

**Describe alternatives you've considered**

**Additional context**

**Comment by samoyin** [comment]
Here is a recreation of the GPAD LED standoff using OpenSCAD.

![image](https://github.com/user-attachments/assets/b7f459de-f705-4646-a58d-71f00ef49ac1)
![image](https://github.com/user-attachments/assets/7bf5ac63-3b0d-4ae6-8f86-101910f7b3de)
These were the measurements that I used to recreate the LED separators. 
Below the measurements is a picture of how the LEDs should look. 

![image](https://github.com/user-attachments/assets/89a99c97-1fd1-49f9-8b88-7e2ac4df6cee)
![image](https://github.com/user-attachments/assets/3ed0f413-4ad8-4909-8de0-7b2d3e30ce06)

**Comment by nk25719** [comment]
After 3D printing the part, the diameter of the side holes can increase to double the diameter size that it is.

**Comment by nk25719** [comment]
please consider the changes done to the Seperator in the file below, 

[5mm_LED_Separator.zip](https://github.com/user-attachments/files/17866768/5mm_LED_Separator.zip)


note: the hight of theseperator will be effected by the hight of the Enclosure. 

cc: @samoyin
