### ISSUE TITLE
Hardware Bug, Workbench Screw holes do not work with M3 screws.

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/PMD___aka-KiCad-esp32-6leds-2switches-1pj-circuit-#75]
**Describe the Failure / Bug**
A clear and concise description of what the failure / bug is.
Short Summary of the expected behavior:  With the work bench file I found on about 20241110, I expected to try to drive an M3 screw to fasten the printed wiring assembly.
Short Summary of the buggy behavior:  The hole is too big for M3 and too small for M4 (the PCB does not allow M4 anyway.)

Here is the Stanly datasheet and design ideas for screws for plastic, the Delta PT.
https://www.stanleyengineeredfastening.com/-/media/web/sef/resources/docs/other/threaded_fasteners_for_plastics.ashx
See the details for an M3 screw for the Boss Design Recommendations
![image](https://github.com/user-attachments/assets/cecbc94e-c733-48af-a717-9d0cef20ab31)

**Comment by nk25719** [comment]
These 3d printed screws fits perfectly inside the workbench holes
[screw 3.2.zip](https://github.com/user-attachments/files/17866755/screw.3.2.zip)



Closing.
